//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated by a tool.
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using RandomPairer.Dal.Entities;

namespace RandomPairer.Dal.Context
{
    public partial class RandomPairerDbContext : DbContext
    {
        public virtual DbSet<User> User { get; set; }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.Secret).HasMaxLength(255);

                entity.HasOne(d => d.Pair)
                    .WithMany(p => p.InversePair)
                    .HasForeignKey(d => d.PairId)
                    .HasConstraintName("fkUserToUser");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
